name: RonanCostello
favicon: null
layout_spectrum: 0.99114
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#180e1b'
    - '#6c6462'
    - '#d7575e'
    - '#a92032'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
